spring:
  application:
    name: gateway-zuul
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#API网关配置
zuul:
  sensitiveHeaders:
  #添加代理头
  add-proxy-headers: true
