server:
  port: 18001

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

foo2: ${foo}2